### ISSUE TITLE
Chrome detection as userscript

### ISSUE THREAD

**Issue by Lambik** [JonDerThan/bookbuyer#1]
For me, the userscript/addon detection didn't work. In tampermonkey + chrome, it passed the original check:

```
function isAddon() {
  return typeof chrome !== "undefined"
}
```

It however worked fine when I changed it to:

```
function isAddon() {
  return typeof chrome !== "undefined" && chrome.runtime
}
```

**Comment by JonDerThan** [comment]
You're right, I've only tested the add-on on Chrome and Firefox, and the userscript on Tampermonkey/Firefox. Apparently I should have been more thorough.

Thanks a lot for reporting the bug and figuring out what caused it! The issue should be fixed now, let me know if you encounter any more problems. :)
