### ISSUE TITLE
Add Author Search Option

### ISSUE THREAD

**Issue by Omar-Ebrahim-1** [JonDerThan/bookbuyer#4]
Instead of searching by book title, search by author name. There is an option to include the author name with the book title, but that messes up the search. Search with only author name.

**Comment by Omar-Ebrahim-1** [comment]
#5

**Comment by JonDerThan** [comment]
What do you mean with "that messes up the search"?

And could you point to an instance where it would be sensible to only search for the author? The add-on inserts links for specific books, why would you exclude the book title from the search?
